# Generated by Django 4.2.6 on 2023-10-25 07:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("publication_date", models.DateField()),
                (
                    "isbn_number",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ISBN must be 10 or 13 digits long.",
                                regex="^(?:\\d{10}|\\d{13})$",
                            )
                        ],
                    ),
                ),
                ("number_of_pages", models.PositiveIntegerField()),
                ("cover_link", models.URLField()),
                (
                    "publication_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ka", "Georgian"),
                            ("pt", "Portuguese"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("de", "German"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.author"
                    ),
                ),
            ],
        ),
    ]
